# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: cocoon 1.2.15 ruby lib

Gem::Specification.new do |s|
  s.name = "cocoon".freeze
  s.version = "1.2.15"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Nathan Van der Auwera".freeze]
  s.date = "2020-09-08"
  s.description = "Unobtrusive nested forms handling, using jQuery. Use this and discover cocoon-heaven.".freeze
  s.email = "nathan@dixis.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".travis.yml",
    "Gemfile",
    "History.md",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "app/assets/javascripts/cocoon.js",
    "cocoon.gemspec",
    "gemfiles/Gemfile.default",
    "gemfiles/Gemfile.rails-3.2.13",
    "gemfiles/Gemfile.rails-4-r2",
    "lib/cocoon.rb",
    "lib/cocoon/view_helpers.rb",
    "lib/generators/cocoon/install/install_generator.rb",
    "npm/README.md",
    "npm/package.json.erb",
    "spec/cocoon_spec.rb",
    "spec/dummy/Rakefile",
    "spec/dummy/app/controllers/application_controller.rb",
    "spec/dummy/app/decorators/comment_decorator.rb",
    "spec/dummy/app/helpers/application_helper.rb",
    "spec/dummy/app/models/comment.rb",
    "spec/dummy/app/models/person.rb",
    "spec/dummy/app/models/post.rb",
    "spec/dummy/app/views/layouts/application.html.erb",
    "spec/dummy/config.ru",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/database.yml",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/development.rb",
    "spec/dummy/config/environments/production.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/initializers/backtrace_silencers.rb",
    "spec/dummy/config/initializers/inflections.rb",
    "spec/dummy/config/initializers/mime_types.rb",
    "spec/dummy/config/initializers/rails_version_helper.rb",
    "spec/dummy/config/initializers/secret_token.rb",
    "spec/dummy/config/initializers/session_store.rb",
    "spec/dummy/config/locales/en.yml",
    "spec/dummy/config/routes.rb",
    "spec/dummy/db/migrate/20110306212208_create_posts.rb",
    "spec/dummy/db/migrate/20110306212250_create_comments.rb",
    "spec/dummy/db/migrate/20110420222224_create_people.rb",
    "spec/dummy/db/schema.rb",
    "spec/dummy/public/404.html",
    "spec/dummy/public/422.html",
    "spec/dummy/public/500.html",
    "spec/dummy/public/favicon.ico",
    "spec/dummy/public/javascripts/application.js",
    "spec/dummy/public/javascripts/controls.js",
    "spec/dummy/public/javascripts/dragdrop.js",
    "spec/dummy/public/javascripts/effects.js",
    "spec/dummy/public/javascripts/prototype.js",
    "spec/dummy/public/javascripts/rails.js",
    "spec/dummy/public/stylesheets/.gitkeep",
    "spec/dummy/script/rails",
    "spec/generators/install_generator_spec.rb",
    "spec/integration/navigation_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/i18n.rb",
    "spec/support/rails_version_helper.rb",
    "spec/support/shared_examples.rb"
  ]
  s.homepage = "http://github.com/nathanvda/cocoon".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.0.8".freeze
  s.summary = "gem that enables easier nested forms with standard forms, formtastic and simple-form".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rails>.freeze, ["~> 4.2"])
      s.add_development_dependency(%q<sqlite3>.freeze, ["= 1.3.13"])
      s.add_development_dependency(%q<json_pure>.freeze, [">= 0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>.freeze, ["~> 3.0.0"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3.0.0"])
      s.add_development_dependency(%q<actionpack>.freeze, [">= 4.0.0"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_development_dependency(%q<rake>.freeze, ["~> 10.1"])
      s.add_development_dependency(%q<nokogiri>.freeze, [">= 0"])
      s.add_development_dependency(%q<generator_spec>.freeze, [">= 0"])
      s.add_development_dependency(%q<rubysl>.freeze, [">= 0"])
      s.add_development_dependency(%q<rubysl-test-unit>.freeze, [">= 0"])
      s.add_development_dependency(%q<psych>.freeze, ["~> 2.2"])
      s.add_development_dependency(%q<racc>.freeze, [">= 0"])
      s.add_development_dependency(%q<rubinius-developer_tools>.freeze, [">= 0"])
    else
      s.add_dependency(%q<rails>.freeze, ["~> 4.2"])
      s.add_dependency(%q<sqlite3>.freeze, ["= 1.3.13"])
      s.add_dependency(%q<json_pure>.freeze, [">= 0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_dependency(%q<rspec-rails>.freeze, ["~> 3.0.0"])
      s.add_dependency(%q<rspec>.freeze, ["~> 3.0.0"])
      s.add_dependency(%q<actionpack>.freeze, [">= 4.0.0"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_dependency(%q<rake>.freeze, ["~> 10.1"])
      s.add_dependency(%q<nokogiri>.freeze, [">= 0"])
      s.add_dependency(%q<generator_spec>.freeze, [">= 0"])
      s.add_dependency(%q<rubysl>.freeze, [">= 0"])
      s.add_dependency(%q<rubysl-test-unit>.freeze, [">= 0"])
      s.add_dependency(%q<psych>.freeze, ["~> 2.2"])
      s.add_dependency(%q<racc>.freeze, [">= 0"])
      s.add_dependency(%q<rubinius-developer_tools>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>.freeze, ["~> 4.2"])
    s.add_dependency(%q<sqlite3>.freeze, ["= 1.3.13"])
    s.add_dependency(%q<json_pure>.freeze, [">= 0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    s.add_dependency(%q<rspec-rails>.freeze, ["~> 3.0.0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.0.0"])
    s.add_dependency(%q<actionpack>.freeze, [">= 4.0.0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<rake>.freeze, ["~> 10.1"])
    s.add_dependency(%q<nokogiri>.freeze, [">= 0"])
    s.add_dependency(%q<generator_spec>.freeze, [">= 0"])
    s.add_dependency(%q<rubysl>.freeze, [">= 0"])
    s.add_dependency(%q<rubysl-test-unit>.freeze, [">= 0"])
    s.add_dependency(%q<psych>.freeze, ["~> 2.2"])
    s.add_dependency(%q<racc>.freeze, [">= 0"])
    s.add_dependency(%q<rubinius-developer_tools>.freeze, [">= 0"])
  end
end

